Improvements and Documentation update
seabee33/screw-scammers pull request #5
Opened 2024-04-28 15:46 UTC by dieperdev

Added a requests session object to improve performance, updated documentation, and made code clearer.

2024-04-28 23:50 UTC, seabee33 approved these changes

2024-04-28 23:50 UTC, seabee33 approved these changes

2024-04-28 23:51 UTC, seabee33 approved these changes

2024-04-28 23:53 UTC, seabee33 requested changes
I'm going to leave this one as I want to make the post variables easy to see and edit as each site will be different with how it names their post data

2024-04-29 00:11 UTC, seabee33 approved these changes
Thank you @dieperdev  :)

2024-04-29 00:11 UTC, merged

2024-04-29 00:31 UTC, dieperdev commented
No problem!